apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    group: backend
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      group: backend
  template:
    metadata:
      labels:
        group: backend
    spec:
      containers:
      - name: server
        image: "dikunmv/kube-stack-server:0.0.1"
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "mongodb://admin:admin@database:27017"
