apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  selector:
    group: database
  ports:
  - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      group: database
  template:
    metadata:
      labels:
        group: database
    spec:
      containers:
      - name: mongo
        image: mongo:4.0.2
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
        volumeMounts:
        - name: database-pv
          mountPath: /data
      volumes:
      - name: database-pv
        persistentVolumeClaim:
          claimName: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
