apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    group: frontend
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      group: frontend
  template:
    metadata:
      labels:
        group: frontend
    spec:
      containers:
      - name: client
        image: "dikunmv/kube-stack-client:0.0.1"
        ports:
        - containerPort: 80
