apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  selector:
    group: database
  ports:
  - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      group: database
  template:
    metadata:
      labels:
        group: database
    spec:
      containers:
      - name: mongo
        image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: database
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        volumeMounts:
        - name: data-pv
          mountPath: /data
      volumes:
      - name: data-pv
        persistentVolumeClaim:
          claimName: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}
