apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  databaseUrl: {{ printf "mongodb://%s:%s@database:27017" .Values.database.username .Values.database.password | b64enc }}
